route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - text: "{{ .CommonAnnotations.summary }}"
        # text: "일어나라!"
        api_url: 'https://hooks.slack.com/services/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'
        channel: 'alert'
        send_resolved: true