server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: none # 배포 시는 none 또는 validate 추천
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
# 객체 스토리지
supabase:
  url: ${SUPABASE_URL}
  bucket-name: ${SUPABASE_BUCKET_NAME}
  access-key: ${SUPABASE_ACCESS_KEY}