server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: none # 배포 시는 none 또는 validate 추천
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # PostgreSQL dialect로 변경
        show_sql: true
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver # PostgreSQL 드라이버로 변경
    url: ${POSTGRES_URL} # PostgreSQL URL로 변경
    username: ${POSTGRES_USERNAME} # PostgreSQL 사용자 이름으로 변경
    password: ${POSTGRES_PASSWORD} # PostgreSQL 비밀번호로 변경
  springdoc:
    swagger-ui:
      enabled: true
    api-docs:
      enabled: true