server:
  port: 8080
spring:
  jpa:
    hibernate:
      # 이것도 dev와 prod를 나눠가져가도 된다
      ddl-auto: validate
      #      ddl-auto: update # 개발 환경에서는 create-drop, 운영 환경에서는 validate 권장
      # 최초 세팅에만 update를 쓰고, 그 이후는 none만 쓰기도 함.
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}